### ISSUE TITLE
Some work along similar lines. 

### ISSUE THREAD

**Issue by aeschylus** [edsilv/trail-examples#2]
Feel free to close the issue, but here are some writings by Mozilla: https://medium.freecodecamp.com/lossless-web-navigation-with-trails-9cd48c0abb56#.dlmggm6n5
https://www.ghacks.net/2017/01/29/trails-lossless-web-navigation-experiment-by-mozilla/

**Comment by edsilv** [comment]
Thanks @aeschylus, I've been in touch with the team at Mozilla (browserhtml.slack.com) and they are definitely thinking along similar lines! 

I've added an issue to the notes repo here to track this: https://github.com/memex/notes/issues/3

I also recently had a chat with @OpenHypervideo and added Joscha's lecture to notes.
